### ISSUE TITLE
Failed Permission check

### ISSUE THREAD

**Issue by Maievmau** [ActiveAgeingHKR/DevicesProxyServer#3]
It's either spamming this:
Info:   Loading application [__admingui] at [/]
Info:   Loading application __admingui done in 11,272 ms
Info:   JACC Policy Provider: Failed Permission Check, context(MainServerREST/MainServerREST)- permission(("javax.security.jacc.WebUserDataPermission" "" "GET"))
Or:
Info:   JACC Policy Provider: Failed Permission Check, context(MainServerREST/MainServerREST)- permission(("javax.security.jacc.WebUserDataPermission" "/api/entities.incidents/isalive" "POST"))

At first i thought it was the MainServerREST, however this only happens in GlassFish's console after i run the MainServer (the proxy server).
Not sure what i did wrong, but they seem to kill eachother and not be able to be run from the same PC.
If i run only one - i don't get this message. But if i run the other, too, one of them will shut down... if not run in the order Proxy > MainSrvr. However, there's still this issue.
I'm posting this here due to the new commit.

**Comment by mineikis** [comment]
hey, i cant reproduce this bug, can you explain more? btw there are new pushes, so maybe try pull and try it more time and let me know if it still exists
